services:
  # Form services for module
  prestashop.tje.type.Client:
    class: 'PrestaShop\tje\Form\ClientType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - '@=service("prestashop.adapter.multistore_feature").isUsed()'
    tags:
      - { name: form.type }

  prestashop.tje.form.identifiable_object.data_provider.client_form_data_provider:
    class: 'PrestaShop\tje\Form\ClientFormDataProvider'
    arguments:
      - '@prestashop.tje.repository.client_repository'

  prestashop.tje.form.identifiable_object.data_handler.client_form_data_handler:
    class: 'PrestaShop\tje\Form\ClientFormDataHandler'
    arguments:
      - '@prestashop.tje.repository.client_repository'
      - '@prestashop.core.admin.lang.repository'
      - '@doctrine.orm.default_entity_manager'

  #Form services for prestashop
  prestashop.tje.form.identifiable_object.handler.client_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.tje.form.identifiable_object.data_handler.client_form_data_handler'
  prestashop.tje.form.identifiable_object.builder.client_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'PrestaShop\tje\Form\ClientType'
      - '@prestashop.tje.form.identifiable_object.data_provider.client_form_data_provider'

  #Repository service
  prestashop.tje.repository.client_repository:
    class: PrestaShop\tje\Repository\ClientRepository
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - PrestaShop\tje\Entity\Client

  # Grid services
  prestashop.tje.grid.definition.factory.Clients:
    class: 'PrestaShop\Module\DemoDoctrine\Grid\Definition\Factory\ClientGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

  prestashop.tje.grid.query_builder.Client:
    class: 'PrestaShop\Module\DemoDoctrine\Grid\Query\ClientQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"

  prestashop.tje.grid.data_provider.Clients:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@prestashop.tje.grid.query_builder.Client'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'Client'

  prestashop.tje.grid.factory.Clients:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@prestashop.tje.grid.definition.factory.Clients'
      - '@prestashop.tje.grid.data_provider.Clients'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'